export const mockProperties = [
    {
        id: 1,
        name: "Modern Apartment in Lagos",
        location: "Victoria Island, Lagos",
        image: "https://images.unsplash.com/photo-1594873604892-b599f847e859?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtb2Rlcm4lMjBhcGFydG1lbnQlMjBpbnRlcmlvcnxlbnwxfHx8fDE3Njg0NzE5NjN8MA&ixlib=rb-4.1.0&q=80&w=1080",
        price: 35000,
        rating: 4.8,
        reviews: 124,
        bedrooms: 3,
        bathrooms: 2,
        guests: 6,
        verified: true,
        amenities: ["WiFi", "Air Conditioning", "Pool", "Parking"]
    },
    {
        id: 2,
        name: "Luxury Villa in Abuja",
        location: "Maitama, Abuja",
        image: "https://images.unsplash.com/photo-1706808849780-7a04fbac83ef?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxsdXh1cnklMjBob3VzZSUyMGV4dGVyaW9yfGVufDF8fHx8MTc2ODQxMTIwOXww&ixlib=rb-4.1.0&q=80&w=1080",
        price: 75000,
        rating: 4.9,
        reviews: 89,
        bedrooms: 5,
        bathrooms: 4,
        guests: 10,
        verified: true,
        amenities: ["WiFi", "Pool", "Gym", "Garden", "Security"]
    },
    {
        id: 3,
        name: "Beachfront Apartment",
        location: "Lekki, Lagos",
        image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxiZWFjaGZyb250JTIwaG91c2V8ZW58MXx8fHwxNzY4NDcyMDEyfDA&ixlib=rb-4.1.0&q=80&w=1080",
        price: 45000,
        rating: 4.7,
        reviews: 156,
        bedrooms: 2,
        bathrooms: 2,
        guests: 4,
        verified: true,
        amenities: ["WiFi", "Beach Access", "Air Conditioning", "Balcony"]
    },
    {
        id: 4,
        name: "Cozy Studio in Ikeja",
        location: "GRA Ikeja, Lagos",
        image: "https://images.unsplash.com/photo-1502672260066-6bc355edcb11?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzdHVkaW8lMjBhcGFydG1lbnR8ZW58MXx8fHwxNzY4NDcyMDM1fDA&ixlib=rb-4.1.0&q=80&w=1080",
        price: 25000,
        rating: 4.6,
        reviews: 98,
        bedrooms: 1,
        bathrooms: 1,
        guests: 2,
        verified: false,
        amenities: ["WiFi", "Air Conditioning", "Kitchenette"]
    },
    {
        id: 5,
        name: "Penthouse Suite",
        location: "Ikoyi, Lagos",
        image: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwZW50aG91c2UlMjBpbnRlcmlvcnxlbnwxfHx8fDE3Njg0NzIwNTF8MA&ixlib=rb-4.1.0&q=80&w=1080",
        price: 95000,
        rating: 5.0,
        reviews: 67,
        bedrooms: 4,
        bathrooms: 3,
        guests: 8,
        verified: true,
        amenities: ["WiFi", "Pool", "Gym", "Concierge", "Parking", "City View"]
    },
    {
        id: 6,
        name: "Family House in Port Harcourt",
        location: "GRA Phase 2, Port Harcourt",
        image: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxmYW1pbHklMjBob3VzZXxlbnwxfHx8fDE3Njg0NzIwNzB8MA&ixlib=rb-4.1.0&q=80&w=1080",
        price: 40000,
        rating: 4.8,
        reviews: 112,
        bedrooms: 4,
        bathrooms: 3,
        guests: 8,
        verified: true,
        amenities: ["WiFi", "Garden", "Parking", "Generator"]
    }
];
